name: "PCK export"
on: push

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: awesomecalculator
  PROJECT_PATH: .

jobs:
  export-pck:
    name: PCK Export
    runs-on: ubuntu-22.04  # Use 22.04 with godot 4
    container:
        image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: PCK Build
        run: |
          mkdir -v -p build/pck
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --import --quit-after 10
          godot --headless --verbose --export-pack "Linux" "$EXPORT_DIR/pck/$EXPORT_NAME.pck"
      - name: Generate sha256
        run: |
          mkdir -v -p checksum/sha256
          EXPORT_DIR="$(readlink -f build)"
          CHECKSUM_DIR="$(readlink -f checksum)"
          sha256sum "$EXPORT_DIR/pck/$EXPORT_NAME.pck" > "$CHECKSUM_DIR/sha256/$EXPORT_NAME.sha256"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pck
          path: build/pck
      - name: Upload Checksum
        uses: actions/upload-artifact@v4
        with:
          name: sha256
          path: checksum/sha256
